[profile.default]
evm_version = "cancun"
solc_version = "0.8.26"
gas_reports = ["*"]
gas_reports_ignore = []
ignored_error_codes = []
verbosity = 3
# Used to deploy deterministically via CREATE2
always_use_create_2_factory = true
bytecode_hash = "none"
cbor_metadata = false
# Use to run Surl in scripts
ffi = true

[profile.production]
optimizer = true
optimizer_runs = 44444444
sizes = true

[fuzz]
runs = 5_000

[invariant]
runs = 512            # The number of calls to make in the invariant tests
depth = 25            # The number of times to run the invariant tests
fail_on_revert = true # Fail the test if the contract reverts

[profile.ci]
optimizer = true
optimizer_runs = 44444444
via_ir = true

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 512
depth = 250

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api" }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
